name: Docker Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install buildx
      run: |
        sudo apt-get update
        sudo apt-get install -y binfmt-support qemu-user-static jq
        mkdir -p ~/.docker/cli-plugins
        BUILDX_URL=$(curl https://api.github.com/repos/docker/buildx/releases/latest | jq -r .assets[].browser_download_url | grep amd64 | grep linux)
        wget $BUILDX_URL -O ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
        docker buildx create --name xbuilder
        docker buildx use xbuilder
        docker buildx inspect --bootstrap

    - name: Log in to GH registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build the Docker image
      run: docker buildx build . --tag ghcr.io/meyskens/docker-desktop-base:$GITHUB_SHA --push --platform "linux/amd64,linux/arm64,linux/arm"
    - name: Tag as and push as latest
      run: |
        docker pull ghcr.io/meyskens/docker-desktop-base:$GITHUB_SHA
        docker tag ghcr.io/meyskens/docker-desktop-base:$GITHUB_SHA ghcr.io/meyskens/docker-desktop-base:latest
        docker push ghcr.io/meyskens/docker-desktop-base:latest

